MAP_COUNTRY_TO_CODE = {
    "Afghanistan": "AF",
    "Albanien": "AL",
    "Algerien": "DZ",
    "Amerikanisch-Samoa": "AS",
    "Andorra": "AD",
    "Angola": "AO",
    "Anguilla": "AI",
    "Antarktis": "AQ",
    "Antigua und Barbados": "AG",
    "Argentinien": "AR",
    "Armenien": "AM",
    "Aruba": "AW",
    "Aserbaidschan": "AZ",
    "Australien": "AU",
    "Bahamas": "BS",
    "Bahrain": "BH",
    "Bangladesch": "BD",
    "Barbados": "BB",
    "Belgien": "BE",
    "Belize": "BZ",
    "Benin": "BJ",
    "Bermudas": "BM",
    "Bhutan": "BT",
    "Bolivien": "BO",
    "Bonaire, Sint Eustatius und Saba": "BQ",
    "Bosnien und Herzegowina": "BA",
    "Botswana": "BW",
    "Bouvetinsel": "BV",
    "Brasilien": "BR",
    "Britisches Territorium im Indischen Ozean": "IO",
    "Brunei Darussalam": "BN",
    "Bulgarien": "BG",
    "Burkina Faso": "BF",
    "Burundi": "BI",
    "Cayman Inseln": "KY",
    "Chile": "CL",
    "China": "CN",
    "Cookinseln": "CK",
    "Costa Rica": "CR",
    "Curaçao": "CW",
    "Demokratische Republik Kongo": "CD",
    "Deutschland": "DE",
    "Dominika": "DM",
    "Dominikanische Republik": "DO",
    "Dschibuti": "DJ",
    "Dänemark": "DK",
    "El Salvador": "SV",
    "Elfenbeinküste": "CI",
    "Equador": "EC",
    "Eritrea": "ER",
    "Estland": "EE",
    "Falklandinseln": "FK",
    "Fidschi-Inseln": "FJ",
    "Finnland": "FI",
    "Frankreich": "FR",
    "Französisch-Guayana": "GF",
    "Französisch-Polynesien": "PF",
    "Französische Süd- und Antarktisgebiete": "TF",
    "Färöer Inseln": "FO",
    "Gabun": "GA",
    "Gambia": "GM",
    "Georgien": "GE",
    "Ghana": "GH",
    "Gibraltar": "GI",
    "Grenada": "GD",
    "Griechenland": "GR",
    "Grönland": "GL",
    "Guadeloupe": "GP",
    "Guam": "GU",
    "Guatemala": "GT",
    "Guernsey": "GG",
    "Guinea": "GN",
    "Guinea-Bissau": "GW",
    "Guyana": "GY",
    "Haiti": "HT",
    "Heard und die McDonaldinseln": "HM",
    "Honduras": "HN",
    "Hongkong": "HK",
    "Indien": "IN",
    "Indonesien": "ID",
    "Irak": "IQ",
    "Iran": "IR",
    "Irland": "IE",
    "Island": "IS",
    "Isle of Man": "IM",
    "Israel": "IL",
    "Italien": "IT",
    "Jamaika": "JM",
    "Japan": "JP",
    "Jemen": "YE",
    "Jersey": "JE",
    "Jordanien": "JO",
    "Jungferninseln (GB)": "VG",
    "Jungferninseln (USA)": "VI",
    "Kambodscha": "KH",
    "Kamerun": "CM",
    "Kanada": "CA",
    "Kapverdische Inseln": "CV",
    "Kasachstan": "KZ",
    "Katar": "QA",
    "Kenia": "KE",
    "Kirgisistan": "KG",
    "Kiribati": "KI",
    "Kokos-Inseln": "CC",
    "Kolumbien": "CO",
    "Komoren": "KM",
    "Kongo": "CG",
    "Kosovo": "XK",
    "Kroatien": "HR",
    "Kuba": "CU",
    "Kuwait": "KW",
    "La Réunion": "RE",
    "Laos": "LA",
    "Lesotho": "LS",
    "Lettland": "LV",
    "Libanon": "LB",
    "Liberia": "LR",
    "Libyen": "LY",
    "Liechtenstein": "LI",
    "Litauen": "LT",
    "Luxemburg": "LU",
    "Macao": "MO",
    "Madagaskar": "MG",
    "Malawi": "MW",
    "Malaysien": "MY",
    "Malediven": "MV",
    "Mali": "ML",
    "Malta": "MT",
    "Marokko": "MA",
    "Marschall-Inseln": "MH",
    "Martinique": "MQ",
    "Mauretanien": "MR",
    "Mauritius": "MU",
    "Mayotte": "YT",
    "Mazedonien, ehem. jugoslawische Republik": "MK",
    "Mexiko": "MX",
    "Mikronesien": "FM",
    "Moldau": "MD",
    "Monaco": "MC",
    "Mongolei": "MN",
    "Montenegro": "ME",
    "Montserrat": "MS",
    "Mosambik": "MZ",
    "Myanmar": "MM",
    "Namibia": "NA",
    "Nauru": "NR",
    "Nepal": "NP",
    "Neukaledonien": "NC",
    "Neuseeland": "NZ",
    "Niederlande": "NL",
    "Niger": "NE",
    "Nigeria": "NG",
    "Nikaragua": "NI",
    "Niue": "NU",
    "Nordkorea": "KP",
    "Norfolk Insel": "NF",
    "Norwegen": "NO",
    "Nördliche Marianen": "MP",
    "Oman": "OM",
    "Pakistan": "PK",
    "Palau": "PW",
    "Panama": "PA",
    "Papua Neu-Guinea": "PG",
    "Paraguay": "PY",
    "Peru": "PE",
    "Philippinen": "PH",
    "Pitcairninseln": "PN",
    "Polen": "PL",
    "Portugal": "PT",
    "Puerto Rico": "PR",
    "Ruanda": "RW",
    "Rumänien": "RO",
    "Russische Föderation": "RU",
    "Saint-Martin (Niederländischer Teil)": "SX",
    "Saint-Martin (franz. Teil)": "MF",
    "Sambia": "ZM",
    "Samoa": "WS",
    "San Marino": "SM",
    "Sankt Bartholomäus": "BL",
    "Saudi Arabien": "SA",
    "Schweden": "SE",
    "Schweiz": "CH",
    "Senegal": "SN",
    "Serbien": "RS",
    "Seychellen": "SC",
    "Sierra Leone": "SL",
    "Simbabwe": "ZW",
    "Singapur": "SG",
    "Slowakei": "SK",
    "Slowenien": "SI",
    "Solomoninseln": "SB",
    "Somalia": "SO",
    "Spanien": "ES",
    "Sri Lanka": "LK",
    "St. Helena, Ascension und Tristan da Cunha": "SH",
    "St. Kitts und Nevis": "KN",
    "St. Lucia": "LC",
    "St. Vincent und die Grenadinen": "VC",
    "St.-Pierre und Miquelon": "PM",
    "Staat Palästina": "PS",
    "Sudan": "SD",
    "Surinam": "SR",
    "Svalbard- und Jan Mayen-Inseln": "SJ",
    "Swasiland": "SZ",
    "Syrien": "SY",
    "São Tomé und Príncipe": "ST",
    "Süd-Georgien und südliche Sandwichinseln": "GS",
    "Südafrika": "ZA",
    "Südkorea": "KR",
    "Südsudan": "SS",
    "Tadschikistan": "TJ",
    "Taiwan": "TW",
    "Tansania": "TZ",
    "Thailand": "TH",
    "Timor-Leste": "TL",
    "Togo": "TG",
    "Tokelau": "TK",
    "Tonga": "TO",
    "Trinidad und Tobago": "TT",
    "Tschad": "TD",
    "Tschechische Republik": "CZ",
    "Tunesien": "TN",
    "Turkmenistan": "TM",
    "Turks- und Caicosinseln": "TC",
    "Tuvalu": "TV",
    "Türkei": "TR",
    "USA - Vereinigte Staaten von Amerika": "US",
    "USA kleinere amerikanische Überseeinseln": "UM",
    "Uganda": "UG",
    "Ukraine": "UA",
    "Ungarn": "HU",
    "Uruguay": "UY",
    "Usbekistan": "UZ",
    "Vanuatu": "VU",
    "Vatikan (Heiliger Stuhl)": "VA",
    "Venezuela": "VE",
    "Vereinigte Arabische Emirate": "AE",
    "Vereinigtes Königreich": "GB",
    "Vietnam": "VN",
    "Wallis und Futuna": "WF",
    "Weihnachtsinseln": "CX",
    "Weißrussland": "BY",
    "Westliche Sahara": "EH",
    "Zentralafrikanische Republik": "CF",
    "Zypern": "CY",
    "Ägypten": "EG",
    "Äquatorialguinea": "GQ",
    "Äthiopien": "ET",
    "Österreich": "AT",
}
